<?php
 // CHAMADA DE CSS
	$this->headLink()->appendStylesheet($this->baseUrl().'/js/jquery-ui/development-bundle/themes/le-frog/jquery.ui.all.css');	
	$this->headLink()->appendStylesheet($this->baseUrl().'/css/estilo.css');	 
	
	
// CHAMADA DE JS  
  $this->headScript()->appendFile($this->baseUrl().'/js/jquery-ui/development-bundle/jquery-1.5.1.js');
  $this->headScript()->appendFile($this->baseUrl().'/js/jquery-ui/development-bundle/external/jquery.bgiframe-2.1.2.js');
  $this->headScript()->appendFile($this->baseUrl().'/js/jquery-ui/development-bundle/ui/jquery.ui.core.js');
  $this->headScript()->appendFile($this->baseUrl().'/js/jquery-ui/development-bundle/ui/jquery.ui.widget.js'); 
  $this->headScript()->appendFile($this->baseUrl().'/js/jquery-ui/development-bundle/ui/jquery.ui.mouse.js');
  
  $this->headScript()->appendFile($this->baseUrl().'/js/jquery-ui/development-bundle/ui/jquery.ui.button.js');
 
  $this->headScript()->appendFile($this->baseUrl().'/js/jquery-ui/development-bundle/ui/jquery.effects.core.js');

 ?>

<div class="span-6">
	<br />Informe usuário e senha
	<?php if(!empty($this->message)) :?>
		<div id="message">
			<?php echo $this->escape($this->message);?>
		</div>
	<?php endif; ?>

	<?php echo $this->form ;?>
</div>

<div class="span-10">
<br />
<br />
<img class="logo" src="<?php echo $this->baseUrl()?>/imagens/cardiologo.jpg"/>

</div>


<script>
	$(function() {
		$( "#Acessar" ).button({
            icons: {
                primary: "ui-icon-circle-check"
            }
        });

		});
</script>
