<!-- PÁGINA/ QUE EXIBE OS XMLs para gera-los (baixa-los) -->
<?php

/* JQGrid Docs: http://www.trirand.com/jqgridwiki/doku.php?id=wiki:jqgriddocs*/
 $this->headLink()->appendStylesheet($this->baseUrl().'/js/jquery-ui/css/le-frog/jquery-ui-1.8.11.custom.css');
 $this->headLink()->appendStylesheet($this->baseUrl().'/css/ui-redmond/ui.multiselect.css'); 
 $this->headLink()->appendStylesheet($this->baseUrl().'/css/jqgrid/ui.jqgrid.css');
 
  
  /* CSS PARA EFEITO NOS BOTOES */
 $this->headLink()->appendStylesheet($this->baseUrl().'/js/jquery-ui/development-bundle/themes/le-frog/jquery.ui.all.css');

 
?>

<div class="span-22 push-2">

	<div class="span-14">

	<br>
	<b><div class="info">XML GERADO COM SUCESSO!</div> </b> 

	<button class="botao" onClick="baixar()">Fazer download</button>
	</div>
	
	<div class="span-18">
<br>
	</div>
	<div class="span-18"> <hr> </div>
	
	
	
	
	
</div>	

<?php

 /* js/jquery-ui/development-bundle/ui  */
 $this->headScript()->appendFile($this->baseUrl().'/js/jquery-ui/development-bundle/ui/jquery.ui.core.js');
 $this->headScript()->appendFile($this->baseUrl().'/js/jquery-ui/development-bundle/ui/jquery.ui.widget.js');
 $this->headScript()->appendFile($this->baseUrl().'/js/jquery-ui/development-bundle/ui/jquery.ui.button.js');

 ?>
 
 	<script>
	$(function() {
		$( ".botao" ).button({
            icons: {
                primary: "ui-icon-plus"
            }
        });
	});
	</script>
	
	
	<script>
function baixar()
{
//document.location.href='/public_html/<?php echo $this->nomeXml; ?>';
window.open("/xml/baixar/lote/"+<?php echo $this->lote; ?>);
}
</script>