SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;


INSERT INTO localdeatendimento (AutoId, Beneficiario, Nome, InicioVigencia, FimVigencia, lote) VALUES
(1, 127, 'UNIMED SANTOS', '2011-04-11', '0000-00-00', 0);
