<!-- ADCIONA EMPRESA  -->
<?php
  /* CSS PARA EFEITO NOS BOTOES */
 $this->headLink()->appendStylesheet($this->baseUrl().'/js/jquery-ui/development-bundle/themes/le-frog/jquery.ui.all.css');
 ?>
<br>


<div class="span-23">

<h3 class="success"> <b> SUCESSO! </b> <br><br>
 A empresa <b><?php foreach($this->empresaAtual as $i => $r){ echo $r['Nome'];}?></b> foi adicionada no sistema </h3>


<br>
<h3 class="erro"> <b> ATENÇÃO </b> <br><br>
Foi gerado automaticamente um usuário e senha<br>
Usuario:<b> <?php echo $this->empresa; ?> </b>
<br>
Senha: <b> unimed </b>
<br>
</h3>

 
<hr>

<h3> Enviar dados por e-mail, digite o e-mail dos destinatários </h3>
		<form name="enviados" id="enviados" method="POST" action="/empresa/envia">	
			<input type="hidden" name="nome" value="<?php echo $this->empresa; ?>" />	
				
					<!-- 1LINHA DE LABEL -->
					<div class="span-7">
					<div class="span-2"><b>E-mail</b></div>
					<div class="span-3"><input type="text" name="email1" id="email" class="email"></div>
					
					</div>
					<div class="span-7">
					<div class="span-2"><b>E-mail</b></div>
					<div class="span-3"><input type="text" name="email2" id="email"></div>
					</div>
					<div class="span-7">
					<div class="span-2"><b>E-mail</b></div>
					<div class="span-3"><input type="text" name="email3" id="email"></div>
					</div>
                                        <br>
					<button class="botao" type="submit">Enviar por e-mail</button>
                                        <br>
                                        <br>
		<br>
		</form>

</div><!-- FIM DO SPAN -->


<?php

 /* js/jquery-ui/development-bundle/ui  */
 $this->headScript()->appendFile($this->baseUrl().'/js/jquery-ui/development-bundle/ui/jquery.ui.core.js');
 $this->headScript()->appendFile($this->baseUrl().'/js/jquery-ui/development-bundle/ui/jquery.ui.widget.js');
 $this->headScript()->appendFile($this->baseUrl().'/js/jquery-ui/development-bundle/ui/jquery.ui.button.js');
  $this->headScript()->appendFile($this->baseUrl().'/js/formularios/jquery.validate.js');

 ?>
 
<script>
$(function() {
        $( ".botao" ).button({
    icons: {
        primary: "ui-icon-plus"
    }
});
});
</script>



<!-- TRATAMENTO DE ERROS -->
<script type="text/javascript">
// QUANDO O DOCUMENTO ESTIVER PRONTO
$(document).ready(function(){
   // CONFIGURA A VALIDACAO DO FORMULARIO
   $("#enviados").validate({
      rules: {
         email1: {required: true}
      },
      messages: {
         email1: {required: '<br>Informe pelo menos um e-mail' }
		 
      }
      ,

   });
});

</script>
	
	